## introduction to scikitlearn(sklearn)
this notebook demostrates some of the most useful functions of the beautfiul scikit-learn libarya
what were going to cover

0.an end to end skitlearn workflow
1. getting the data ready
2. choose the right estimator/ algorithm fr our problem
3. fit the modle/algorithm and use it maek predixtionsn on our data
4. evluat a modle
5. improve a model 
6. save and load a trained model
7.  putting it all toghter!


## 0. an end to end scikit-learn workflow

In [1]:
# 1 get the data ready
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
#create x (feautres matrix)
x = heart_disease.drop("target", axis = 1)

#create y Label
y = heart_disease["target"]

In [3]:
# 2 choose the right model and hyper parameter
from sklearn.ensemble import RandomForestClassifier
clf= RandomForestClassifier()

#we'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
#3 fit the model to the traning data 
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [5]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [6]:
#y_label = clf.predict(np.array([0,2,3,4]))

In [7]:
y_pred = clf.predict(x_test)
y_pred


array([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [8]:
y_test

169    0
186    0
135    1
105    1
299    0
      ..
296    0
67     1
79     1
217    0
148    1
Name: target, Length: 61, dtype: int64

In [9]:
#4. evaluate the model on the training data and test data
clf.score(x_train,y_train)

1.0

In [10]:
clf.score(x_test,y_test)

0.7704918032786885

In [11]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.66      0.73        29
           1       0.74      0.88      0.80        32

    accuracy                           0.77        61
   macro avg       0.78      0.77      0.77        61
weighted avg       0.78      0.77      0.77        61



In [12]:
confusion_matrix(y_test,y_pred)


array([[19, 10],
       [ 4, 28]], dtype=int64)

In [13]:
accuracy_score(y_test,y_pred)

0.7704918032786885

In [14]:
#5 imporve a model
#try different amout of n_estators
np.random.seed(45)
for i in range(10,100,10):
    print(f"trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"Model accuracy on test set: {clf.score(x_test,y_test)* 100:.2f}%")
    print("")

trying model with 10 estimators...
Model accuracy on test set: 72.13%

trying model with 20 estimators...
Model accuracy on test set: 78.69%

trying model with 30 estimators...
Model accuracy on test set: 83.61%

trying model with 40 estimators...
Model accuracy on test set: 75.41%

trying model with 50 estimators...
Model accuracy on test set: 80.33%

trying model with 60 estimators...
Model accuracy on test set: 78.69%

trying model with 70 estimators...
Model accuracy on test set: 78.69%

trying model with 80 estimators...
Model accuracy on test set: 77.05%

trying model with 90 estimators...
Model accuracy on test set: 80.33%



In [15]:
#6 save a model and load it 
import pickle
pickle.dump(clf,open("random_forest_model_1.pkl","wb"))

In [16]:
loaded_model = pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.score(x_test,y_test)

0.8032786885245902

#getting the data ready to be used fwth machine leaning
three main things we have to do:
1. split the data into features and label(usally 'x' and 'y')
2. filling(also calle
    d imputing) or disregarding missig values
3. converting non-numerical values to numerical values(also called featurer encoding)
    

In [17]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [18]:
x = heart_disease.drop("target",axis=1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [19]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [20]:
#split the data into training and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_tain,y_test = train_test_split(x,y,test_size=(0.2))

In [21]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [22]:
x.shape[0]*0.8

242.4

In [23]:
len(heart_disease)

303

# 1.1 make sure its all numerical

In [24]:
car_sales = pd.read_csv("car-sales.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [25]:
len(car_sales)

10

In [26]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [27]:
# split into x/y
x = car_sales.drop("Price",axis=1)
y = car_sales["Price"]

#split into training and test
x_train,x_test,y_train,y_test = train_test_split(x,
                                                 y,
                                                 test_size = 0.2)

In [28]:
# One-hot encode categorical features in x_train and x_test
x_train = pd.get_dummies(x_train, drop_first=True)
x_test = pd.get_dummies(x_test, drop_first=True)

# Align x_train and x_test columns to ensure they match after encoding
x_train, x_test = x_train.align(x_test, join='left', axis=1, fill_value=0)

# Import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

# Preprocess y_train and y_test to remove dollar signs and commas
y_train = y_train.replace(r'[\$,]', '', regex=True).astype(float)
y_test = y_test.replace(r'[\$,]', '', regex=True).astype(float)

# Fit the model
model = RandomForestRegressor()
model.fit(x_train, y_train)

# Score the model
score = model.score(x_test, y_test)
print("Model score:", score)


Model score: -46.86009


In [29]:
#trun the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                
                               remainder = "passthrough")
transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 1.50043e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 8.78990e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 3.25490e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 1.00000e+00, 1.11790e+04],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 2.13095e+05],
       [0.00000e+00, 0.00000e+

In [30]:
pd.DataFrame(transformed_x)

0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  150043.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   87899.0
2  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   32549.0
3  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   11179.0
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  213095.0
5  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0   99213.0
6  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   45698.0
7  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   54738.0
8  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   60000.0
9  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   31600.0

In [31]:
dummies = pd.get_dummies(car_sales[["Make","Colour","Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4     False       False        False         True         False   
1      4     False        True        False        False         False   
2      3     False       False        False         True         False   
3      5      True       False        False        False          True   
4      4     False       False         True        False         False   
5      4     False       False        False         True         False   
6      4     False        True        False        False         False   
7      4     False        True        False        False         False   
8      4     False       False        False         True         False   
9      4     False       False         True        False         False   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0        False         False       False          True  
1        False         False        True         False  
2         True         False       False         False  
3        False         False       False         False  
4        False         False       False          True  
5        False          True       False         False  
6         True         False       False         False  
7         True         False       False         False  
8        False         False       False          True  
9        False         False       False          True

In [32]:
# Preprocess y to remove dollar signs and commas
y = y.replace(r'[\$,]', '', regex=True).astype(float)

# Now split the data
np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)

# Fit the model
model.fit(x_train, y_train)


RandomForestRegressor()

In [33]:
# Preprocess y to remove dollar signs and commas before splitting
y = y.replace(r'[\$,]', '', regex=True).astype(float)

# Now split the data
from sklearn.model_selection import train_test_split
np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)

# Fit the model
model.fit(x_train, y_train)

# Score the model
score = model.score(x_test, y_test)
print("Model score:", score)


Model score: -1.2793638399999998


### what if there were missing value?
1. fill them with some value(also known as imputation)
2. remove sampels with missing data altogether



In [34]:
#import car sales missing data
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500

In [35]:
car_sales_missing.isna().sum

<bound method DataFrame.sum of     Make  Colour  Odometer  Doors  Price
0  False   False     False  False  False
1  False   False     False  False  False
2  False   False      True  False  False
3  False   False     False  False  False
4  False   False     False  False  False
5  False   False      True  False  False
6  False    True      True  False  False
7  False   False      True  False   True
8  False   False     False   True   True
9   True   False     False  False  False>

In [36]:
#create  and y 
x = car_sales_missing.drop("Price", axis = 1)
y = car_sales_missing["Price"]

In [37]:
car_sales_missing

Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

### option 1 : fill missing data with pandsa

In [38]:
#check our dataframe again
car_sales_missing.isna().sum()

Make        1
Colour      1
Odometer    4
Doors       1
Price       2
dtype: int64

In [39]:
# remove rows with missing price value
car_sales_missing.dropna(inplace =True)

In [40]:
car_sales_missing.isna().sum()

Make        0
Colour      0
Odometer    0
Doors       0
Price       0
dtype: int64

In [41]:
len(car_sales_missing)

4

In [42]:
x = car_sales_missing.drop("Price",axis = 1)
y =  car_sales_missing["Price"]

In [43]:
#trun the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                
                               remainder = "passthrough")
transformed_x = transformer.fit_transform(car_sales_missing)
transformed_x

array([[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 150043.0, '$4,000'],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 87899.0, '$5,000'],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 11179.0, '$22,000'],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 213095.0, '$3,500']],
      dtype=object)

### opton 2 fill missing value with scikitlearn

In [44]:
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500

In [45]:
#drop te rows with no labels 
car_sales_missing.dropna(subset=["Price"],inplace=True)
car_sales_missing.isna().sum()

Make        1
Colour      1
Odometer    3
Doors       0
Price       0
dtype: int64

In [46]:
#split into x and y
x = car_sales_missing.drop("Price",axis=1)
y = car_sales_missing["Price"]

In [47]:
#fill missing values with sckit-learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#fill categorcal values with missing and numerical values with mean
cat_imputer = SimpleImputer(strategy = "constant",fill_value="missing")
door_imputer = SimpleImputer(strategy = "constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

#define columns
cat_features=["Make","Colour"]
door_features = ["Doors"]
num_features = ["Odometer"]

#create an mputer something to fill data 
imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer,door_features),
    ("num_imputer",num_imputer,num_features)
])
#transform the data
filled_x = imputer.fit_transform(x)
filled_x

array([['Toyota', 'White', 4.0, 150043.0],
       ['Honda', 'Red', 4.0, 87899.0],
       ['Toyota', 'Blue', 3.0, 98763.2],
       ['BMW', 'Black', 5.0, 11179.0],
       ['Nissan', 'White', 4.0, 213095.0],
       ['Toyota', 'Green', 4.0, 98763.2],
       ['Honda', 'missing', 4.0, 98763.2],
       ['missing', 'White', 4.0, 31600.0]], dtype=object)

In [48]:
car_sales_filled = pd.DataFrame(filled_x,
                               columns = ["make","Colour","Doors","Odometer"])
car_sales_filled

make   Colour Doors  Odometer
0   Toyota    White   4.0  150043.0
1    Honda      Red   4.0   87899.0
2   Toyota     Blue   3.0   98763.2
3      BMW    Black   5.0   11179.0
4   Nissan    White   4.0  213095.0
5   Toyota    Green   4.0   98763.2
6    Honda  missing   4.0   98763.2
7  missing    White   4.0   31600.0

In [49]:
car_sales_filled.isna().sum()

make        0
Colour      0
Doors       0
Odometer    0
dtype: int64

In [50]:
#trun the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                
                               remainder = "passthrough")
transformed_x = transformer.fit_transform(car_sales_filled)
transformed_x

<8x15 sparse matrix of type '<class 'numpy.float64'>'
	with 32 stored elements in Compressed Sparse Row format>

In [51]:
# Preprocess y to remove dollar signs and commas and convert to float
y = y.replace(r'[\$,]', '', regex=True).astype(float)

# Now proceed with train/test split and model fitting
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Split the data
x_train, x_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)

# Initialize and fit the model
model = RandomForestRegressor()
model.fit(x_train, y_train)

# Score the model
score = model.score(x_test, y_test)
print("Model score:", score)


Model score: -116.89768


In [52]:
len(car_sales_filled),len(car_sales)

(8, 10)

## 2 chossing the right estmator/algorthm for your probelm

some things to note:

* sklearn reffers to machine learning models,algorthms  as estimator

* classification provelm - predictin a caegory (heart disease or not)
    * sometimes youll see clf short for classifier used as a classification estimator 
* Regression probelm - predictin a number selling prce of a car

In [53]:
#get califiornia houseing dataset
from sklearn.datasets import fetch_california_housing
housing= fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [54]:
housing_df = pd.DataFrame(housing["data"],columns=housing["feature_names"])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [55]:
housing_df["target"]= housing["target"]
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [56]:
#housing_df = housing_df.drop("MedHouseVal",axis=1)

In [57]:
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [58]:
#import algorith
from sklearn.linear_model import Ridge 
#setup random seed
np.random.seed(42)

#create the data
x= housing_df.drop("target",axis=1)
y = housing_df["target"] #median house price in 100,000

#split into train and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,)

#nstiatinte and fit the mondel
model = Ridge()
model.fit(x_train,y_train)

#cjheck the score of the model 
model.score(x_test,y_test)

0.5911128551684497

what if 'ridge didn't woke or the score ddn't fit our work


we can always try another model 

how abou  we try a ensebmle model an sensembl is a combination of smaller models to try and mak beter preditions

In [59]:
#iimport the RandomFrstRegressor model clss from the ensmble module

#setup rando seed
np.random.seed(42)

#create the data 
x = housing_df.drop("target", axis=1)
y= housing_df["target"]

#split into train and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size  = 0.2)

#create random forest model
model = RandomForestRegressor()
model.fit(x_train,y_train)

#check the score of the model
model.score(x_test,y_test)

0.8065734772187598

### 2.2 picking a machin learning model for a classification probelm

In [60]:
hear_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [61]:
len(heart_disease)

303

In [63]:
#import  the lineaersvc estimator class
from sklearn.svm import LinearSVC

#set up random seed
np.random.seed(42)

#make data

x = heart_disease.drop("target", axis =1)
y = heart_disease["target"]

#split data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

#instantaite LinearSVC
clf = LinearSVC(max_iter = 10000)
clf.fit(x_train,y_train)

#evalvuate the linear svc
clf.score(x_test,y_test)

0.8688524590163934

In [64]:
heart_disease["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [68]:
#import  the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

#set up random seed
np.random.seed(42)

#make data

x = heart_disease.drop("target", axis =1)
y = heart_disease["target"]

#split data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

#instantaite random forest classifier
clf = RandomForestClassifier(n_estimators = 100)
clf.fit(x_train,y_train)

#evalvuate the Random forest classifier
clf.score(x_test,y_test)

0.8524590163934426

Tidbit:
1. if you have structured data used ensembl methods
2. if you have unstruced data use deeplearning or trnasferleraning 

In [69]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

## 3. fit the model/aglorithm on our data and use it to make predictions

### 3.1 fitting the modle to our data
different names for:
* 'x'= features,features variables,data
* 'y' =labels,targets,target variables

In [72]:
#import  the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

#set up random seed
np.random.seed(42)

#make data

x = heart_disease.drop("target", axis =1)
y = heart_disease["target"]

#split data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

#instantaite random forest classifier
clf = RandomForestClassifier(n_estimators = 100)


#fit the model to the data (trianing the machine learning model)
clf.fit(x_train,y_train)

#evalvuate the Random forest classifier(use the patterns the model has learned)
clf.score(x_test,y_test)

0.8524590163934426

### 3.2 make predictions useing a machine learining model 

2 ways to make preidcitions:
1. 'predict()'
2. predict_proba()

In [73]:
# use a trianed model to make a precitions
clf.predict(np.array([1,7,8,3,4])) # this doesn't work...

C:\Users\genjo\Desktop\sample_project_1\env\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 7. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [76]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
249   69    1   2       140   254    0        0      146      0      2.0   
104   50    1   2       129   196    0        1      163      0      0.0   
300   68    1   0       144   193    1        1      141      0      3.4   
193   60    1   0       145   282    0        0      142      1      2.8   
184   50    1   0       150   243    0        0      128      0      2.6   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2  
..     ...  ..   ...  
249      1   3     3  
104      2   0     2  
300      1   2     3  
193      1   2     3  
184      1   0     3  

[61 rows x 13 columns]

In [77]:
x_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [78]:
y_test

179    0
228    0
111    1
246    0
60     1
      ..
249    0
104    1
300    0
193    0
184    0
Name: target, Length: 61, dtype: int64

In [79]:
clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [80]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [82]:
#compare predicitions to truth label to evaluate the model
y_preds = clf.predict(x_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [83]:
clf.score(x_test,y_test)

0.8524590163934426

In [85]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

make prediciton with predic_proba()

In [88]:
# make a prediciton with predic_proba()
clf.predict_proba(x_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [90]:
#lets predict() n the same data
clf.predict(x_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [91]:
heart_disease["target"].value_counts()


target
1    165
0    138
Name: count, dtype: int64

In [93]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [94]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

#create the data 
x = housing_df.drop("target",axis=1)
y = housing_df["target"]

#split into training and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#create model instance
model = RandomForestRegressor()

#fit model to data 
model.fit(x_train,y_train)

# Make predictions
y_pred = model.predict(x_test)

In [95]:
y_preds[:10]

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1], dtype=int64)

In [96]:
y_test[:10]

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
13311    1.58700
7113     1.98200
7668     1.57500
18246    3.40000
5723     4.46600
Name: target, dtype: float64

In [97]:
np.array(y_test[]:10)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3838281875.py, line 1)